#!/usr/bin/env node
// Regenerate briefs/README.md (the index: human navigator on GitHub + the context
// skill's selection surface) from brief frontmatter, and register the briefs root
// in ~/.clearvoid/roots.json. Deterministic — no LLM. Run at the end of every compile.
//
// Usage: node buildIndex.mjs --briefs-dir <path>

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { registerRoot } from "./lib.mjs";

function arg(name) {
	const i = process.argv.indexOf(name);
	return i >= 0 ? process.argv[i + 1] : undefined;
}

const briefsDir = arg("--briefs-dir");
if (!briefsDir) {
	console.error("buildIndex: usage: node buildIndex.mjs --briefs-dir <path>");
	process.exit(1);
}

// Minimal frontmatter read: scalar fields + the first line of a `field: |` block.
function readFrontmatter(text) {
	const m = text.match(/^---\n([\s\S]*?)\n---/);
	if (!m) return null;
	const head = m[1];
	const fm = {};
	for (const key of ["title", "summary", "updated", "created"]) {
		const v = head.match(new RegExp(`^${key}:\\s*(.+)$`, "m"));
		if (v) fm[key] = v[1].trim();
	}
	const block = head.match(/^framing:\s*\|\s*\n((?:[ \t]+.*\n?)+)/m);
	if (block) {
		fm.framing = block[1]
			.split("\n")
			.map((l) => l.trim())
			.filter(Boolean)
			.join(" ");
	} else {
		const inline = head.match(/^framing:\s*(.+)$/m);
		if (inline) fm.framing = inline[1].trim();
	}
	return fm;
}

const files = readdirSync(resolve(briefsDir)).filter(
	(f) => f.endsWith(".md") && f !== "README.md",
);

const rows = [];
for (const f of files) {
	const fm = readFrontmatter(readFileSync(join(briefsDir, f), "utf8"));
	if (!fm?.title) continue;
	const blurb =
		fm.summary ?? (fm.framing ? fm.framing.split(". ")[0].replace(/\.?$/, ".") : "");
	rows.push({ file: f, title: fm.title, blurb, updated: fm.updated ?? "" });
}
rows.sort((a, b) => b.updated.localeCompare(a.updated) || a.title.localeCompare(b.title));

const lines = [
	"# Briefs",
	"",
	"_Generated by [clearvoid](https://github.com/clearvoid/skills) — do not edit; run `/clearvoid:compile` to refresh. One line per brief: the current compiled view of this repo's work._",
	"",
	...rows.map(
		(r) =>
			`- **[${r.title}](${encodeURI(r.file)})** — ${r.blurb}${r.updated ? ` _(updated ${r.updated})_` : ""}`,
	),
	"",
];
writeFileSync(join(briefsDir, "README.md"), lines.join("\n"));

const registered = registerRoot(briefsDir);
console.log(
	`buildIndex: ${rows.length} briefs indexed${registered ? "; root registered in roots.json" : ""}`,
);
